/*
Locator = identifies the elements in the page
DOM- Document Object Model

HTML!=DOM, both are different

DOM generated by HTML of the page

HTML+JS source code request sent to a domain ( e.g:google), it generates a DOM
------------------------------------------------------
| DOM is an API interface provided by every browser  |
------------------------------------------------------


All locators identify by DOM itself, that's why DOM is imp

These are the recommended built-in locators.

page.getByRole() to locate by explicit and implicit accessibility attributes.
page.getByText() to locate by text content.(non interactive elements)
page.getByLabel() to locate a form control by associated label's text.
page.getByPlaceholder() to locate an input by placeholder.
page.getByAltText() to locate an element, usually image, by its text alternative.
page.getByTitle() to locate an element by its title attribute.
page.getByTestId() to locate an element based on its data-testid attribute (other attributes can be configured).


*/

//locator is also one of the fixture

import {test,expect,Locator} from "@playwright/test"

test("verify playwright locators",async ({page})=>{

    await page.goto("http://127.0.0.1:5500/practice-app/frontend/pages/locators.html")

    //1.page.getByAltText() - identify images (and similar elements) based on the alt attribute
   //Use this locator when your element support alt text such as, img and area elements

   const image1:Locator = page.getByAltText("A scenic mountain view"); // type of variable is Locator
    // await is not necessary here, because getByAltText() is not async function, it doesn't return a promise, it returns a locator object
   // image1.click(); //here await is not necessary, because click() is not async function, it doesn't return a promise, it returns void

   await expect(image1).toBeVisible(); //here await is necessary, because toBeVisible() is async function, it returns a promise
   //here we performing some action and assertion so, await statement is required

   //ALWAYS USE AWAIT WHEN YOU ARE PERFORMING SOME ACTION OR ASSERTION ON LOCATOR OBJECT, OTHERWISE AWAIT IS NOT REQUIRED



   //2.page.getByText() - identify elements based on their text content. you can match by a substring, exact string.
   //Use this locator to find non interactive elements  like div, span, p, h1-h6, etc. 
   //Locate by visible text content, not hidden text content
   //For interactive elements like button, a, input, etc use role locator
   

   const text:Locator= page.getByText("This paragraph has completely unique text content. "); 
   await expect(text).toBeVisible();
   const partialText:Locator= page.getByText("This paragraph has completely "); // provided substring
   await expect(partialText).toBeVisible();

   const regulagExpressionText:Locator= page.getByText(/This\s+Paragraph\s+Has/i); // provided substring as regular expression, here 'i' is for case insensitive
   await expect(regulagExpressionText).toBeVisible();





   //3.page.getByRole() - Locating by Role (Role is not an attribute of element )
   /* Role locators include buttons, checkboxes, headings, links, lists, tables, and many more
   andfollow W3C specifications for ARIA role.
   Prefer for interactive elements like buttons, checkboxes, links, lists, headings, tables etc.

   Note that many html elements like <button> have an implicitly defined role that is recognized by the role locator.

   implicitly defined role  is nothing but the tagname of the element and the role name of the element are same

   explicitly defined role  is nothing but the tagname of the element and the role name of the element are different
   
   */

   await page.getByRole("link",{name:'Nav Link'}).click();
   const headerNonInteractiveElement:Locator= page.getByRole("heading",{name:'List of common HTML elements and their corresponding ARIA roles'});
   //you can also use getByText()
   await expect(headerNonInteractiveElement).toBeVisible();


   //4.page.getByLabel() - to locate a form control by associated label's text.
   /* Especially used for form control (only forms)
   When to use : Ideal for form fields with visible labels

   
   */

    await  page.getByLabel('Label via for/id').fill("test getByLabel");
    await  page.getByLabel('Wrapped Label Input ').fill("test getByLabel");


    //5. page.getByPlaceholder() - Finds element with a given placeholder text
    //Best for inputs without a label but having a placeholder
    await page.getByPlaceholder("Enter your username").fill("satyans");
    await page.getByPlaceholder("Enter your user email").fill("satyanarayan.sahoo@aetna.com");

    //6. page.getBytitle() - to locate an element by its title attribute
    //When to use : when you element has a meaningful title attribute


    const saveTitle:Locator=  page.getByTitle("Save your changes");
    expect(saveTitle).toHaveText("Save");
    await page.getByTitle("Additional context info").click();

    //7. page.getByTestId() - to locate an element by it testId attribute
    //one advantage of this attribute is , it's customizable
    //When to use: when text or role-based locators are unstable or not suitable
   

    await expect(page.getByTestId("testid-standard-btn")).toHaveText("Standard data-testid button");
    await expect(page.getByTestId("filter-add-to-cart-1")).toHaveText("Add to cart");
   //await expect(page.getByTestId("custom-qa-btn")).toHaveText("Custom data-qa button (configure testIdAttribute)"); // for this test case, we have to configure testIdAttribute in playwright.config.ts file, because the attribute name is not data-testid, it's data-qa

})